// Package pingapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package pingapi

// Defines values for PongResponseMessage.
const (
	Pong PongResponseMessage = "pong"
)

// Valid indicates whether the value is a known member of the PongResponseMessage enum.
func (e PongResponseMessage) Valid() bool {
	switch e {
	case Pong:
		return true
	default:
		return false
	}
}

// PongResponse Body of GET /ping.
type PongResponse struct {
	// Echo The `msg` query parameter, echoed back; absent when it was not given.
	Echo *string `json:"echo,omitempty"`

	// Message Always "pong".
	Message PongResponseMessage `json:"message"`
}

// PongResponseMessage Always "pong".
type PongResponseMessage string

// VersionResponse Build identity of the running binary — the same document the admin
// listener serves on /version (libs/httpx.BuildInfo).
type VersionResponse struct {
	// BuildTime vcs.time, RFC 3339, empty when unknown.
	BuildTime string `json:"build_time"`

	// GoVersion Go toolchain version.
	GoVersion string `json:"go_version"`

	// Modified Built from a dirty tree.
	Modified bool `json:"modified"`

	// Revision VCS revision when built from a checkout, else "unknown".
	Revision string `json:"revision"`

	// Service Service name.
	Service string `json:"service"`

	// Version Version stamped at build time (libs/httpx.Version); "dev" locally.
	Version string `json:"version"`
}

// PingOpsPingParams defines parameters for PingOpsPing.
type PingOpsPingParams struct {
	Msg *string `form:"msg,omitempty" json:"msg,omitempty"`
}
