// Package tasksapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package tasksapi

import (
	"time"
)

// CreateTaskRequest Body of POST /tasks.
type CreateTaskRequest struct {
	// Title Title of the task; an empty title is rejected with a 400 problem.
	Title string `json:"title"`
}

// Problem RFC 9457 problem details. Extension members are inlined (RFC 9457 §3.2).
type Problem struct {
	// Code Stable machine-readable code for business errors (e.g. task_not_found).
	Code *string `json:"code,omitempty"`

	// Detail Human-readable explanation specific to this occurrence.
	Detail *string `json:"detail,omitempty"`

	// Instance URI reference identifying this occurrence (the request path).
	Instance *string `json:"instance,omitempty"`

	// Status HTTP status of this occurrence — always equals the response status.
	Status int32 `json:"status"`

	// Title Short, human-readable summary of the problem type.
	Title string `json:"title"`

	// Type URI reference identifying the problem type; "about:blank" when generic.
	Type string `json:"type"`
}

// Task A single to-do item.
type Task struct {
	// CreatedAt Creation time, RFC 3339 UTC.
	CreatedAt time.Time `json:"created_at"`

	// Done Completion flag.
	Done bool `json:"done"`

	// Id Server-assigned identifier (UUID).
	Id string `json:"id"`

	// Title Human-readable title; never empty.
	Title string `json:"title"`
}

// TaskList Body of GET /tasks: newest first, at most 100 entries.
type TaskList struct {
	Tasks []Task `json:"tasks"`
}

// TasksOpsCreateJSONRequestBody defines body for TasksOpsCreate for application/json ContentType.
type TasksOpsCreateJSONRequestBody = CreateTaskRequest
