// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package events

// Published when a task is deleted (event_type task.deleted).
type TaskDeletedEvent struct {
	// Unique id of this event (UUID), also the event_id header.
	EventId string `json:"event_id" yaml:"event_id" mapstructure:"event_id"`

	// Task identifier (UUID), also the record key.
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// The last version the task had.
	Version int `json:"version" yaml:"version" mapstructure:"version"`
}
