// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package events

// Published when a task's title or done flag changes (event_type task.updated).
type TaskUpdatedEvent struct {
	// Completion flag after the change.
	Done bool `json:"done" yaml:"done" mapstructure:"done"`

	// Unique id of this event (UUID), also the event_id header.
	EventId string `json:"event_id" yaml:"event_id" mapstructure:"event_id"`

	// Task identifier (UUID), also the record key.
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// Title after the change.
	Title string `json:"title" yaml:"title" mapstructure:"title"`

	// The task's version after the change; a consumer can drop an older one than it
	// has seen.
	Version int `json:"version" yaml:"version" mapstructure:"version"`
}
