// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package events

import "time"

// Published to the `tasks.events` topic when a task is created; key = task id.
type TaskCreatedEvent struct {
	// Creation time, RFC 3339 UTC.
	CreatedAt time.Time `json:"created_at" yaml:"created_at" mapstructure:"created_at"`

	// Task identifier (UUID), also the record key.
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// Task title at creation time.
	Title string `json:"title" yaml:"title" mapstructure:"title"`
}
